
get http://localhost:3002/items
content-Type: application/json


###

post http://localhost:3002/items
content-Type: application/json

{
    "title":"becycle",
    "description":"16 inc wheels",
    "userName": "Sonia",
    "price": 5,
    "photo": "becycle's photo"
    
}
###

