
get http://localhost:3002/items
content-Type: application/json


###

post http://localhost:3002/items
content-Type: application/json

{
    "title":"becycle",
    "description":"16 inc wheels",
    "userName": "Sonia",
    "price": 5,
    "photo": "becycle's photo"
    
}
###


get http://localhost:3002/comments/5
content-Type: application/json


### Insert new comment


post http://localhost:3002/comments
content-Type: application/json

{
    "commentBody":"What a price?",
    "ItemId": 5       
}
###
delete http://localhost:3002/comments/12
content-Type: application/json



### Registration


post http://localhost:3002/auth
content-Type: application/json

{
    "userName":"Olivia",
    "password": "korova"
}

### Login

post http://localhost:3002/auth/login
content-Type: application/json

{
    "userName":"Oliv",
    "password": "korova"
}

